import { NextRequest, NextResponse } from "next/server";
import { verifySession } from "@/lib/session";
import prisma from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  try {
    const token = req.cookies.get("sde_session")?.value;
    if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const user = verifySession(token) as any;
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const accessToken = req.cookies.get("ds_access_token")?.value;
    if (!accessToken) {
      return NextResponse.json({ error: "DocuSign not connected", needsAuth: true }, { status: 401 });
    }

    const { applicationId } = await req.json();
    if (!applicationId) return NextResponse.json({ error: "applicationId required" }, { status: 400 });

    const application = await prisma.application.findUnique({ where: { id: applicationId } });
    if (!application) return NextResponse.json({ error: "Application not found" }, { status: 404 });

    const accountId = process.env.DOCUSIGN_ACCOUNT_ID!;
    const baseUrl = process.env.DOCUSIGN_BASE_URL!;

    const signerEmail = application.email || "";
    const signerName = [application.firstName, application.lastName].filter(Boolean).join(" ") || "Applicant";
    const dealerEmail = user.email || "";
    const dealerName = user.firstName ? `${user.firstName} ${user.lastName || ""}`.trim() : "Dealer Representative";
    const dealNumber = application.dealNumber || applicationId;

    if (!signerEmail) {
      return NextResponse.json({ error: "Applicant email required to send for signature" }, { status: 400 });
    }

    // Build document HTML
    const documentHtml = `
<!DOCTYPE html>
<html>
<head><style>
body { font-family: Arial, sans-serif; margin: 40px; color: #111; }
h1 { font-size: 24px; color: #0f0f0f; }
h2 { font-size: 16px; color: #C9A84C; border-bottom: 1px solid #C9A84C; padding-bottom: 4px; }
table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
td { padding: 8px 12px; border: 1px solid #ddd; font-size: 13px; }
td:first-child { font-weight: bold; background: #f8f6f1; width: 40%; }
.footer { font-size: 11px; color: #999; margin-top: 40px; border-top: 1px solid #eee; padding-top: 12px; }
</style></head>
<body>
<h1>Smart Drive Elite — Deal Summary</h1>
<p>Deal Number: <strong>${dealNumber}</strong> &nbsp;|&nbsp; Date: ${new Date().toLocaleDateString()}</p>

<h2>Applicant Information</h2>
<table>
<tr><td>Name</td><td>${signerName}</td></tr>
<tr><td>Email</td><td>${signerEmail}</td></tr>
<tr><td>Phone</td><td>${application.phone || "—"}</td></tr>
</table>

<h2>Vehicle & Deal Structure</h2>
<table>
<tr><td>Vehicle</td><td>${application.vehicleYear || ""} ${application.vehicleMake || ""} ${application.vehicleModel || ""}</td></tr>
<tr><td>Vehicle Price</td><td>$${(application.vehiclePrice || 0).toLocaleString()}</td></tr>
<tr><td>Down Payment</td><td>$${(application.downPayment || 0).toLocaleString()}</td></tr>
<tr><td>Amount Financed</td><td>$${(application.amountFinanced || 0).toLocaleString()}</td></tr>
</table>

<h2>Approval Terms</h2>
<table>
<tr><td>Lender</td><td>${application.lender || "—"}</td></tr>
<tr><td>Tier</td><td>${application.tier || "—"}</td></tr>
<tr><td>Max Monthly Payment</td><td>$${(application.maxPayment || 0).toLocaleString()}/mo</td></tr>
<tr><td>APR</td><td>${application.apr ? (Number(application.apr) * 100).toFixed(2) + "%" : "—"}</td></tr>
<tr><td>Term</td><td>${application.termMonths || "—"} months</td></tr>
</table>

<p style="margin-top:40px;">By signing below, I acknowledge that I have reviewed and agree to the terms of this deal summary. Final approval and funding are subject to lender review.</p>

<br/><br/>
<table style="border:none;">
<tr>
<td style="border:none; width:45%;">
  <div style="border-bottom: 1px solid #000; height: 40px;"></div>
  <p style="font-size:12px;">Applicant Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date</p>
</td>
<td style="border:none; width:10%;"></td>
<td style="border:none; width:45%;">
  <div style="border-bottom: 1px solid #000; height: 40px;"></div>
  <p style="font-size:12px;">Dealer Representative Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date</p>
</td>
</tr>
</table>

<div class="footer">Smart Drive Elite LLC | Smithville, MO 64089 | USPTO Trademark #99764274 | License #2763<br/>
This document is generated by Smart Drive Elite. Approval and funding are not guaranteed.</div>
</body>
</html>`;

    const documentBase64 = Buffer.from(documentHtml).toString("base64");

    const envelope = {
      emailSubject: `Smart Drive Elite — Deal ${dealNumber} Ready for Signature`,
      emailBlurb: `Your deal summary for ${signerName} is ready for review and signature. Please review the terms and sign at your earliest convenience.`,
      documents: [{
        documentBase64,
        name: `Deal_Summary_${dealNumber}.html`,
        fileExtension: "html",
        documentId: "1",
      }],
      recipients: {
        signers: [
          {
            email: signerEmail,
            name: signerName,
            recipientId: "1",
            routingOrder: "1",
            tabs: {
              signHereTabs: [{ documentId: "1", pageNumber: "1", xPosition: "100", yPosition: "650" }],
              dateSignedTabs: [{ documentId: "1", pageNumber: "1", xPosition: "300", yPosition: "650" }],
            },
          },
          {
            email: dealerEmail,
            name: dealerName,
            recipientId: "2",
            routingOrder: "2",
            tabs: {
              signHereTabs: [{ documentId: "1", pageNumber: "1", xPosition: "450", yPosition: "650" }],
              dateSignedTabs: [{ documentId: "1", pageNumber: "1", xPosition: "650", yPosition: "650" }],
            },
          },
        ],
      },
      status: "sent",
    };

    const envelopeRes = await fetch(`${baseUrl}/restapi/v2.1/accounts/${accountId}/envelopes`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(envelope),
    });

    if (!envelopeRes.ok) {
      const err = await envelopeRes.text();
      console.error("DocuSign envelope error:", err);
      return NextResponse.json({ error: "Failed to create envelope", details: err }, { status: 500 });
    }

    const envelopeData = await envelopeRes.json();
    const envelopeId = envelopeData.envelopeId;

    await prisma.application.update({
      where: { id: applicationId },
      data: {
        docusignEnvelopeId: envelopeId,
        docusignStatus: "SENT",
        docusignSentAt: new Date(),
      },
    });

    return NextResponse.json({
      success: true,
      envelopeId,
      message: `Deal summary sent to ${signerEmail} for signature`,
    });
  } catch (error: any) {
    console.error("DocuSign send error:", error);
    return NextResponse.json({ error: error.message || "Failed to send" }, { status: 500 });
  }
}
